#archivo para levantar varios contenedores a la vez
services:

  db:
    build: ./db

    image: casino-db:latest
    container_name: casino-db

    environment:
      POSTGRES_USER: casino
      POSTGRES_PASSWORD: casino
      POSTGRES_DB: casino_db

    volumes:
      - pg_data:/var/lib/postgresql/data

    networks:
      - casino-net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U casino -d casino_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    build: .

    image: casino-backend:latest
    container_name: casino-backend

    ports:
      - "3000:3000"

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy

    networks:
      - casino-net

  frontend:
    build:
      context: ../frontend_intro_devops_casino

    image: casino-frontend:latest
    container_name: casino-frontend

    ports:
      - "80:8080"

    environment:
      BACKEND_HOST: "backend"

    depends_on:
      - backend

    networks:
      - casino-net

networks:
  casino-net:
    driver: bridge

volumes:
  pg_data: