apiVersion: v1
kind: Secret
metadata:
  name: casino-secrets
  namespace: vidalcasino
type: Opaque
stringData:
  DB_HOST: "casino-db"
  DB_PORT: "5432"
  DB_USER: "casino"
  DB_PASSWORD: "casino"
  DB_NAME: "casino_db"
  JWT_SECRET: "cambiame-por-un-secreto-real"
  JWT_EXPIRES_IN: "1d"
  CORS_ORIGIN: "*"
  BACKEND_HOST: "casino-backend"