apiVersion: v1
kind: Service
metadata:
  name: casino-apuestas
  namespace: vidalcasino
spec:
  type: ClusterIP
  selector:
    app: casino-apuestas
  ports:
    - port: 8005
      targetPort: 8005
      protocol: TCP